import { main } from '../utils/schematics-cli'
import { createConsoleLogger } from '@angular-devkit/core/node'
import { CliConfigItem, GenerateItem } from '../config.dto'
import { LoadConfig } from '../utils/load-config'

const CONFIG = LoadConfig()

interface DirCliItem extends GenerateItem {
  parentPath?: string
  child?: DirCliItem[]
}

export async function generateCustom(config: CliConfigItem) {
  const dirs = config.generate
  const logger = createConsoleLogger(false)

  if (!dirs || !dirs.length) return
  for (let i = 0; i < dirs.length; i++) {
    try {
      dirs[i].templatePath = dirs[i].templatePath || config.templatePath
      dirs[i].handlerPath = dirs[i].handlerPath || config.handlerPath
      await callSchematics(dirs[i], config)
    } catch (e) {
      logger.warn(e.message)
    }
  }
}

async function callSchematics(
  dir: DirCliItem,
  config: CliConfigItem,
  parentDir?: DirCliItem
) {
  const { name, parentPath = '', templatePath } = dir

  let args: string[] = []
  args = ['@cvue/cli:custom', `--name=${name}`]
  parentPath && args.push(`--modulePath=${parentPath}`)
  templatePath && args.push(`--templatePath=${templatePath}`)
  await main({
    args,
    isAutoGenerated: true,
    itemConfig: config
  })

  if (dir.child) {
    for (let i = 0; i < dir.child.length; i++) {
      const child = dir.child[i]
      if (parentDir) {
        child.parentPath = `${parentPath}/${name}`
      } else {
        child.parentPath = name
      }
      await callSchematics(child, config, dir)
    }
  }
}
