import { main } from '../utils/schematics-cli'
import { createConsoleLogger } from '@angular-devkit/core/node'
import { CliConfigItem, GenerateItem } from '../config.dto'
import { LoadConfig } from '../utils/load-config'
import { colors } from '../utils/terminal'

const CONFIG = LoadConfig()

interface ViewDirCliItem extends GenerateItem {
  parentPath?: string
  child?: ViewDirCliItem[]
}

export async function generateView(config: CliConfigItem) {
  const dirs = config.generate
  const logger = createConsoleLogger(false)

  if (!dirs || !dirs.length) return
  for (let i = 0; i < dirs.length; i++) {
    try {
      dirs[i].templatePath = dirs[i].templatePath || config.templatePath
      dirs[i].handlerPath = dirs[i].handlerPath || config.handlerPath
      await callSchematics(dirs[i], config)
    } catch (e) {
      logger.warn(e.message)
    }
  }
}

async function callSchematics(
  dir: ViewDirCliItem,
  config: CliConfigItem,
  parentDir?: ViewDirCliItem
) {
  throwTypeError(dir, parentDir)

  const { name, viewType = 'page', parentPath = '', templatePath, handlerPath } = dir
  const viewPath = config.root

  let args: string[] = []
  switch (viewType) {
    case 'module':
      args = ['@cvue/cli:module', `--name=${name}`]
      parentPath && args.push(`--modulePath=${parentPath}`)
      templatePath && args.push(`--templatePath=${templatePath}`)
      handlerPath && args.push(`--handlerPath=${handlerPath}`)
      await main({
        args,
        isAutoGenerated: true,
        itemConfig: config
      })
      break
    case 'page':
      args = ['@cvue/cli:view', `--name=${name}`]
      parentPath && args.push(`--modulePath=${parentPath}`)
      templatePath && args.push(`--templatePath=${templatePath}`)
      handlerPath && args.push(`--handlerPath=${handlerPath}`)
      console.log(args)
      await main({
        args,
        isAutoGenerated: true,
        itemConfig: config
      })
      break
    case 'component':
      args = [
        '@cvue/cli:dependent',
        `--name=${name}`,
        `--hostPath=${viewPath}/${parentPath}`,
      ]
      templatePath && args.push(`--templatePath=${templatePath}`)
      handlerPath && args.push(`--handlerPath=${handlerPath}`)
      await main({
        args,
        isAutoGenerated: true,
        itemConfig: config
      })
  }

  if (dir.child) {
    for (let i = 0; i < dir.child.length; i++) {
      const child = dir.child[i]
      if (parentDir) {
        if (parentDir.viewType === 'module') {
          child.parentPath = `${parentPath}/${name}`
        } else if (parentDir.viewType === 'component') {
          child.parentPath = `${parentPath}/components/${name}`
        } else {
          child.parentPath = `${parentPath}/src/components/${name}`
        }
      } else {
        child.parentPath = name
      }
      await callSchematics(child, config, dir)
    }
  }
}

function throwTypeError(dir: ViewDirCliItem, parentDir?: ViewDirCliItem) {
  if (dir.viewType === 'module' && parentDir && parentDir.viewType !== 'module') {
    throw new Error(
      `${colors.red('ERROR')} module:${dir.name}只能在是module的child中！`
    )
  }
  if (dir.viewType === 'page' && parentDir && parentDir.viewType !== 'module') {
    throw new Error(
      `${colors.red('ERROR')} page:${dir.name}只能在是module的child中！`
    )
  }
  if (
    dir.viewType === 'component' &&
    (!parentDir ||
      !(parentDir.viewType === 'page' || parentDir.viewType === 'component'))
  ) {
    throw new Error(
      `${colors.red('ERROR')} component:${dir.name}不能写在model或者顶层！`
    )
  }
}
